In [1]:
import numpy as np
import pandas as pd

In [2]:
raw_files = "../data/raw_files/"
processed_files = "../data/processed_files/"

# load cleaned marketing dataset
marketing_kpi = pd.read_csv(processed_files + "clean_marketing_product.csv")

#### KPI for Marketing Data

In [3]:
marketing_kpi.head(3)

,campaign_id,product_id,budget,clicks,conversions,revenue_generated,roi,customer_id,subscription_tier,subscription_length,flash_sale_id,discount_level,units_sold,bundle_id,bundle_price,customer_satisfaction_post_refund,common_keywords
0,CMP_RLSDVN,PROD_HBJFA3,41770.45,4946,73,15520.09,1.94,CUST_1K7G39,Premium,4,FLASH_1VFK5K,43,34,BNDL_29U6W5,433.80,4,Affordable
1,CMP_JHHUE9,PROD_OE8YNJ,29900.93,570,510,30866.17,0.76,CUST_0DWS6F,Premium,4,FLASH_1M6COK,28,97,BNDL_ULV60J,289.29,2,Innovative
2,CMP_6SBOWN,PROD_4V8A08,22367.45,3546,265,32585.62,1.41,CUST_BR2GST,Basic,9,FLASH_J4PEON,51,160,BNDL_0HY0EF,462.87,4,Affordable

In [4]:
# ROAS = Return on Ad Spend (Revenue / Budget)
marketing_kpi["roas"] = np.where(marketing_kpi["budget"] > 0,
                                 marketing_kpi["revenue_generated"] / marketing_kpi["budget"], np.nan)

# ROI (Recalculated) = (Revenue - Budget) / Budget
marketing_kpi["roi_recalc"] = np.where(marketing_kpi["budget"] > 0,
                                       (marketing_kpi["revenue_generated"] - marketing_kpi["budget"]) / marketing_kpi["budget"], np.nan)

# CPC = Cost per Click (Budget / Clicks)
marketing_kpi["cpc"] = np.where(marketing_kpi["clicks"] > 0,
                                marketing_kpi["budget"] / marketing_kpi["clicks"], np.nan)

# CPA = Cost per Acquisition (Budget / Conversions)
marketing_kpi["cpa"] = np.where(marketing_kpi["conversions"] > 0,
                                marketing_kpi["budget"] / marketing_kpi["conversions"], np.nan)

# Conversion Rate = Conversions / Clicks
marketing_kpi["conversion_rate"] = np.where(marketing_kpi["clicks"] > 0,
                                            marketing_kpi["conversions"] / marketing_kpi["clicks"], np.nan)

# Revenue per Click = Revenue / Clicks
marketing_kpi["revenue_per_click"] = np.where(marketing_kpi["clicks"] > 0,
                                              marketing_kpi["revenue_generated"] / marketing_kpi["clicks"], np.nan)

# AOV = Average Order Value (Revenue / Conversions)
marketing_kpi["avg_order_value"] = np.where(marketing_kpi["conversions"] > 0,
                                            marketing_kpi["revenue_generated"] / marketing_kpi["conversions"], np.nan)

# Replace infinite values (from divide by zero) with NaN
marketing_kpi = marketing_kpi.replace([np.inf, -np.inf], np.nan)

marketing_kpi.head(10)

,campaign_id,product_id,budget,clicks,conversions,revenue_generated,roi,customer_id,subscription_tier,subscription_length,...,bundle_price,customer_satisfaction_post_refund,common_keywords,roas,roi_recalc,cpc,cpa,conversion_rate,revenue_per_click,avg_order_value
0,CMP_RLSDVN,PROD_HBJFA3,41770.45,4946,73,15520.09,1.94,CUST_1K7G39,Premium,4,...,433.80,4,Affordable,0.371557,-0.628443,8.445299,572.197945,0.014759,3.137907,212.603973
1,CMP_JHHUE9,PROD_OE8YNJ,29900.93,570,510,30866.17,0.76,CUST_0DWS6F,Premium,4,...,289.29,2,Innovative,1.032281,0.032281,52.457772,58.629275,0.894737,54.151175,60.521902
2,CMP_6SBOWN,PROD_4V8A08,22367.45,3546,265,32585.62,1.41,CUST_BR2GST,Basic,9,...,462.87,4,Affordable,1.456832,0.456832,6.307798,84.405472,0.074732,9.189402,122.964604
3,CMP_Q31QCU,PROD_A1Q6ZB,29957.54,2573,781,95740.12,3.32,CUST_6TBY6K,Premium,32,...,334.16,1,Durable,3.195861,2.195861,11.643039,38.357926,0.303537,37.209530,122.586581
4,CMP_AY0UTJ,PROD_F57N66,36277.19,818,79,81990.43,3.53,CUST_XASI45,Standard,29,...,371.67,2,Affordable,2.260110,1.260110,44.348643,459.204937,0.096577,100.232800,1037.853544
5,CMP_5F4E9W,PROD_2CF719,41159.74,1259,763,65792.30,0.77,CUST_GH04I5,Basic,31,...,194.93,2,Affordable,1.598462,0.598462,32.692407,53.944613,0.606037,52.257585,86.228440
6,CMP_WDWHH6,PROD_QN8SL7,32787.71,3882,29,54205.71,4.84,CUST_TRQ4H8,Basic,9,...,232.09,1,Stylish,1.653233,0.653233,8.446087,1130.610690,0.007470,13.963346,1869.162414
7,CMP_JECPN0,PROD_FN0KK1,38372.99,230,350,82083.18,0.74,CUST_XOGUSD,Premium,18,...,211.59,4,Stylish,2.139087,1.139087,166.839087,109.637114,1.521739,356.883391,234.523371
8,CMP_WWJQBU,PROD_12IBBU,13332.96,4657,349,95260.16,0.75,CUST_5RON6U,Premium,2,...,495.94,4,Affordable,7.144712,6.144712,2.862993,38.203324,0.074941,20.455263,272.951748
9,CMP_G2GXC0,PROD_HBPOK5,33407.18,3027,963,25569.45,2.15,CUST_VPSNHS,Basic,35,...,488.82,2,Durable,0.765388,-0.234612,11.036399,34.690737,0.318137,8.447126,26.551869

#### KPI for Web Campaign Data

In [5]:
campaign_kpi = pd.read_csv(processed_files + "clean_campaign.csv")

In [6]:
# Conversion Rate = Conversions / Page Views (proxy for impressions)
campaign_kpi["conversion_rate"] = np.where(campaign_kpi["page_views"] > 0,
                                           campaign_kpi["conversions"] / campaign_kpi["page_views"], np.nan)

# ARPU = Average Revenue per User
campaign_kpi["arpu"] = np.where(campaign_kpi["new_user"] >= 0,  # include both new and existing users
                                campaign_kpi["revenue"], np.nan)

# Revenue per Session = Revenue / Sessions (here each row = one session)
campaign_kpi["revenue_per_session"] = np.where(campaign_kpi["session_duration"] > 0,
                                               campaign_kpi["revenue"], np.nan)

# Engagement Rate = Page Views / Session Duration (pages per minute approx.)
campaign_kpi["engagement_rate"] = np.where(campaign_kpi["session_duration"] > 0,
                                           campaign_kpi["page_views"] / campaign_kpi["session_duration"], np.nan)

# Replace infinite values
campaign_kpi = campaign_kpi.replace([np.inf, -np.inf], np.nan)

campaign_kpi.head(10)

,date,user_id,session_duration,page_views,source,medium,campaign,device_category,country,new_user,conversions,revenue,conversion_rate,arpu,revenue_per_session,engagement_rate
0,2023-06-06,1,448,7,Referral,Direct,Spring Promo,Tablet,USA,1,2,124,0.285714,124.0,124.0,0.015625
1,2023-06-19,2,94,1,Referral,Social Media,Summer Sale,Desktop,India,1,1,130,1.000000,130.0,130.0,0.010638
2,2023-06-29,3,595,6,Direct,Referral,Winter Campaign,Tablet,India,1,1,136,0.166667,136.0,136.0,0.010084
3,2023-06-01,4,263,9,Social,Organic Search,NaN,Tablet,Australia,1,0,0,0.000000,0.0,0.0,0.034221
4,2023-06-30,5,242,1,Referral,Referral,Spring Promo,Tablet,USA,0,0,0,0.000000,0.0,0.0,0.004132
5,2023-06-30,6,421,6,Organic,Direct,Summer Sale,Desktop,Germany,1,3,318,0.500000,318.0,318.0,0.014252
6,2023-06-21,7,359,6,Referral,Direct,Summer Sale,Desktop,Canada,0,1,67,0.166667,67.0,67.0,0.016713
7,2023-06-20,8,448,9,Organic,Direct,NaN,Desktop,Germany,1,3,315,0.333333,315.0,315.0,0.020089
8,2023-06-07,9,185,8,Referral,Referral,Winter Campaign,Desktop,Canada,1,1,59,0.125000,59.0,59.0,0.043243
9,2023-06-08,10,379,3,Direct,Social Media,Winter Campaign,Mobile,India,1,3,339,1.000000,339.0,339.0,0.007916

##### Aggregating Campaign data

In [7]:
#  add a sessions counter per row
campaign_kpi["sessions"] = 1

# aggregate
grp_cols = ["date","source","medium","campaign","device_category"]
agg = (campaign_kpi.groupby(grp_cols, dropna=False).agg(
           sessions=("sessions","sum"),
           page_views=("page_views","sum"),
           conversions=("conversions","sum"),
           revenue=("revenue","sum"),
           session_duration=("session_duration","sum"),
           new_users=("new_user","sum"),
       )
       .reset_index())

# derived metrics on the aggregate
agg["cvr_per_session"] = np.where(agg["sessions"]>0, agg["conversions"]/agg["sessions"], np.nan)      # conversions per session
agg["cvr_per_pageview"] = np.where(agg["page_views"]>0, agg["conversions"]/agg["page_views"], np.nan) # conversions per page view
agg["arpu"] = np.where(agg["sessions"]>0, agg["revenue"]/agg["sessions"], np.nan)                      # avg revenue per session
agg["avg_session_duration"] = np.where(agg["sessions"]>0, agg["session_duration"]/agg["sessions"], np.nan)
agg["avg_pages_per_session"] = np.where(agg["sessions"]>0, agg["page_views"]/agg["sessions"], np.nan)
agg["new_user_rate"] = np.where(agg["sessions"]>0, agg["new_users"]/agg["sessions"], np.nan)

agg.head(10)

,date,source,medium,campaign,device_category,sessions,page_views,conversions,revenue,session_duration,new_users,cvr_per_session,cvr_per_pageview,arpu,avg_session_duration,avg_pages_per_session,new_user_rate
0,2023-06-01,Direct,Direct,Spring Promo,Desktop,1,4,0,0,390,1,0.000000,0.000000,0.000000,390.00,4.00,1.000000
1,2023-06-01,Direct,Direct,Spring Promo,Mobile,3,12,4,437,738,2,1.333333,0.333333,145.666667,246.00,4.00,0.666667
2,2023-06-01,Direct,Direct,Spring Promo,Tablet,1,9,0,0,534,1,0.000000,0.000000,0.000000,534.00,9.00,1.000000
3,2023-06-01,Direct,Direct,Summer Sale,Desktop,1,10,0,0,595,0,0.000000,0.000000,0.000000,595.00,10.00,0.000000
4,2023-06-01,Direct,Direct,Summer Sale,Tablet,4,29,2,257,999,1,0.500000,0.068966,64.250000,249.75,7.25,0.250000
5,2023-06-01,Direct,Direct,Winter Campaign,Desktop,2,20,4,410,854,1,2.000000,0.200000,205.000000,427.00,10.00,0.500000
6,2023-06-01,Direct,Direct,Winter Campaign,Mobile,2,10,3,216,381,2,1.500000,0.300000,108.000000,190.50,5.00,1.000000
7,2023-06-01,Direct,Direct,Winter Campaign,Tablet,2,9,4,353,933,1,2.000000,0.444444,176.500000,466.50,4.50,0.500000
8,2023-06-01,Direct,Direct,NaN,Desktop,1,1,3,348,452,1,3.000000,3.000000,348.000000,452.00,1.00,1.000000
9,2023-06-01,Direct,Direct,NaN,Mobile,2,7,1,147,633,1,0.500000,0.142857,73.500000,316.50,3.50,0.500000

In [8]:
# Load cleaned SEO dataset
s_path = processed_files + "clean_seo_keywords.csv"
seo_kpi = pd.read_csv(s_path)

# Keyword Opportunity Score:
# higher search volume, lower CPC, lower competition = better opportunity
seo_kpi["opp_score"] = (
    seo_kpi["search_volume"].rank(pct=True)        # higher volume is better
    - seo_kpi["cpc"].rank(pct=True)                # lower CPC is better
    - seo_kpi["score"].rank(pct=True)              # lower SEO difficulty score is better
)

# Normalize between 0–1
seo_kpi["opp_score"] = (seo_kpi["opp_score"] - seo_kpi["opp_score"].min()) / \
                       (seo_kpi["opp_score"].max() - seo_kpi["opp_score"].min())

seo_kpi.head(10)

,keyword,cpc,search_volume,competition,score,opp_score
0,email marketing,1.74,27100,low,0.4350,0.506349
1,emailing marketing,1.74,27100,low,0.4350,0.506349
2,marketing emails,1.44,22200,low,0.3600,0.542857
3,email templates,0.91,9900,low,0.2275,0.730159
4,what is email advertising,0.49,6600,low,0.1225,0.804762
5,what is email marketing,0.49,6600,low,0.1225,0.804762
6,email marketing tools,2.43,5400,low,0.6075,0.441270
7,images of email,0.00,3600,low,0.0000,1.000000
8,email images,0.00,3600,low,0.0000,1.000000
9,image for email,0.00,3600,low,0.0000,1.000000

In [9]:
def classify_intent(keyword):
    k = keyword.lower()
    if any(w in k for w in ["what", "how", "definition", "examples", "sample", "meaning", "strategy", "course", "class"]):
        return "informational"
    elif any(w in k for w in ["tools", "software", "platform", "services", "best", "free", "template", "campaign"]):
        return "transactional"
    elif any(w in k for w in ["job", "career", "position", "work"]):
        return "career"
    elif any(w in k for w in ["image", "pic", "picture", "photo", "question"]):
        return "misc"
    else:
        return "generic"

seo_kpi["intent"] = seo_kpi["keyword"].apply(classify_intent)
seo_kpi.head(10)

,keyword,cpc,search_volume,competition,score,opp_score,intent
0,email marketing,1.74,27100,low,0.4350,0.506349,generic
1,emailing marketing,1.74,27100,low,0.4350,0.506349,generic
2,marketing emails,1.44,22200,low,0.3600,0.542857,generic
3,email templates,0.91,9900,low,0.2275,0.730159,transactional
4,what is email advertising,0.49,6600,low,0.1225,0.804762,informational
5,what is email marketing,0.49,6600,low,0.1225,0.804762,informational
6,email marketing tools,2.43,5400,low,0.6075,0.441270,transactional
7,images of email,0.00,3600,low,0.0000,1.000000,misc
8,email images,0.00,3600,low,0.0000,1.000000,misc
9,image for email,0.00,3600,low,0.0000,1.000000,misc

In [10]:
seo_summary = seo_kpi.groupby("intent")[["search_volume","cpc","score","opp_score"]].mean().round(2)
seo_summary

               search_volume   cpc  score  opp_score
intent
career               1356.36  0.06   0.01       0.78
generic              5291.25  0.83   0.21       0.54
informational        1203.53  1.16   0.29       0.53
misc                 1014.50  0.01   0.00       0.80
transactional        1381.35  2.20   0.55       0.33

In [11]:
# Save marketing KPIs
marketing_kpi.to_csv(processed_files + "kpi_marketing.csv", index=False)

# Save campaign KPIs (row-level with metrics)
campaign_kpi.to_csv(processed_files + "kpi_campaign.csv", index=False)

# Save campaign aggregates (daily/channel summaries)
agg.to_csv(processed_files + "agg_campaign_daily.csv", index=False)

# Save SEO KPIs (with intent + opportunity score)
seo_kpi.to_csv(processed_files + "kpi_seo.csv", index=False)

# Save SEO summary by intent
seo_summary.to_csv(processed_files + "agg_seo_summary_by_intent.csv", index=False)

print("All KPI files saved to:", processed_files)

All KPI files saved to: ../data/processed_files/

In [12]:
# Load your daily aggregate
agg = pd.read_csv(processed_files + "agg_campaign_daily.csv")

agg.head(3)

,date,source,medium,campaign,device_category,sessions,page_views,conversions,revenue,session_duration,new_users,cvr_per_session,cvr_per_pageview,arpu,avg_session_duration,avg_pages_per_session,new_user_rate
0,2023-06-01,Direct,Direct,Spring Promo,Desktop,1,4,0,0,390,1,0.000000,0.000000,0.000000,390.0,4.0,1.000000
1,2023-06-01,Direct,Direct,Spring Promo,Mobile,3,12,4,437,738,2,1.333333,0.333333,145.666667,246.0,4.0,0.666667
2,2023-06-01,Direct,Direct,Spring Promo,Tablet,1,9,0,0,534,1,0.000000,0.000000,0.000000,534.0,9.0,1.000000

In [13]:
# Heuristic channel mapping from source/medium → traffic_type
def map_traffic(row):
    s = str(row.get("source", "")).lower()
    m = str(row.get("medium", "")).lower()
    if any(x in m for x in ["cpc","ppc","paid","ads"]) or any(x in s for x in ["google ads","facebook","meta","linkedin","bing ads"]):
        return "Paid"
    if "organic" in m or "organic" in s:
        return "Organic"
    if "email" in m or "email" in s:
        return "Email"
    if "referral" in m or "referral" in s:
        return "Referral"
    if "social" in m or any(x in s for x in ["facebook","twitter","linkedin","instagram","youtube","tiktok"]):
        return "Social"
    if "direct" in s or m in ["(none)","none","direct"]:
        return "Direct"
    return "Other"

agg["traffic_type"] = agg.apply(map_traffic, axis=1)

# Save a compact table for the dashboard
mix = (agg.groupby(["date","traffic_type"], dropna=False)
          .agg(sessions=("sessions","sum"),
               page_views=("page_views","sum"),
               conversions=("conversions","sum"),
               revenue=("revenue","sum"))
          .reset_index())

mix_path = processed_files + "traffic_mix_daily.csv"
mix.to_csv(mix_path, index=False)
print("saved →", mix_path)
mix.head(10)

saved → ../data/processed_files/traffic_mix_daily.csv

         date traffic_type  sessions  page_views  conversions  revenue
0  2023-06-01       Direct        40         215           57     5384
1  2023-06-01      Organic       141         828          229    23329
2  2023-06-01     Referral       100         543          181    18744
3  2023-06-01       Social        43         211           58     5979
4  2023-06-02       Direct        36         176           48     4630
5  2023-06-02      Organic       143         755          213    20732
6  2023-06-02     Referral       106         593          166    17406
7  2023-06-02       Social        36         210           42     4173
8  2023-06-03       Direct        43         235           74     7108
9  2023-06-03      Organic       140         773          210    20532